### ISSUE TITLE
[DESKTOP CSS] Ajustes de CSS

### ISSUE THREAD

**Issue by estercmandrade** [conselhoindigenistamissionario/caci#90]
- [x] Ajustar altura do botão zoom in/out do mapa.
![Captura de Tela 2023-10-09 às 15 29 18](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/1a90664f-032b-41c0-8b80-2434ea9987a7)

- [x] Ajustar ícone de camadas e legendas (encavalando).
![Captura de Tela 2023-10-09 às 16 04 51](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/e7f451d2-d360-462a-8fd3-63c31930de7d)

CASOS
- [x] Exibir botão zoom in/out do mapa ao lado quando lista de Casos estiver aberta.
Atual: ![Captura de Tela 2023-10-09 às 15 17 18](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/81101499-8345-4e41-8a9d-e7692a4734ea)

Layout: ![Captura de Tela 2023-10-09 às 15 17 07](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/1f8b12a0-1f69-4a7c-a7ff-b7291b938970)

- [x] Ajustar modal com a lista de casos. Se a altura da tela for maior que 920px, o modal começa a se deslocar para baixo:
![Captura de Tela 2023-10-09 às 15 27 51](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/601ed451-cc93-45a9-be04-fe406e97c70f)

SINGLE MODAL
- [x] Ajustar localização do modal single de caso. Ao selecionar um caso, o modal é exibido pequeno e "flutuando" na página.
![Captura de Tela 2023-10-09 às 15 32 33](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/edcf77f2-c91c-4d07-9950-7817e3032dcd)

- [x] Ajustar cor e cor de fundo dos botão de navegação entre os casos e o botão fechar.
- [x] Ao rolar o scroll dentro do modal, cabeçalho deve rolar junto (atualmente está fixo).
- [x] Ajustar espaçamento entre os ícones de compartilhamento e o conteúdo do caso.
![Captura de Tela 2023-10-09 às 15 40 27](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/38182fc7-1372-42f8-94cd-a48982b5aed4)

- [x] Ajustar cor do texto de descrição do caso para #111111.
- [x] Ajustar largura do texto "Fonte:CIMI: A Violência Contra os Povos Indígenas no Brasil - 2008" e cor para #777777.
- [x] #98

DOSSIÊ (modal com lista dossiê).
- [x] Ao rolar o scroll dentro do modal, cabeçalho deve rolar junto (atualmente está fixo).
- [x] #97
- [x] #96

SINGLE DOSSIE
- [x] Ajustar localização do modal single de caso. Ao selecionar um caso, o modal é exibido pequeno e "flutuando" na página.
![Captura de Tela 2023-10-09 às 16 01 06](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/6520df3b-24dd-409d-837d-f6335e0635ac)

- [x] Resolução menor que 870px de altura, o modal é exibido atras do menu.
- [x] #95
- [x] Alterar cor do texto e dos ícones de compartilhamento para #666666.

COMPARTILHE
- [x] Ajustar borda e cor do botão fechar
![Captura de Tela 2023-10-09 às 16 06 25](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/e5608acf-0710-416b-8d67-22515ee4ad96)

A CACI
- [x] Ajustar tamanho da fonte dos itens do menu para 18px e remover borda entre os itens do menu.
- [x] Ajustar espessura do texto "Desenvolvido por".
